server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: BfXw386lJux5cLJ6L2WakQGVqHmSjx1I
        url: jdbc:postgresql://dpg-cmlq2ha1hbls73cb8ngg-a.oregon-postgres.render.com:5432/halalbakespreview
        username: zachary
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
springfox:
    documentation:
        swagger-ui:
            enabled: true
        open-api:
            enabled: true

openfoodfacts:
    feign:
        url: https://world.openfoodfacts.net/api/v2
