openapi: 3.0.3
info:
  title: Halal Bakes API
  description: API endpoint for Android app
  version: 1.0.0
basePath: "/v3/api-docs"

paths:
  /get-prod-info:
    get:
      tags:
        - Hbv1
      summary: Main API endpoint
      operationId: getProdInfo
      parameters:
        - name: barcode
          in: query
          description: Barcode number passed through scan
          schema:
            type: string
      responses:
        '200':
          description: Simplified model of information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdInfoModel'
  /get-all-questions:
    get:
      tags:
        - Hbv1
      summary: Get all the forum questions
      operationId: getAllQuestions
      responses:
        '200':
          description: List of all the forum questions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionInfoModel'
  /get-open-food-facts-model:
    get:
      tags:
        - Hbv1
      summary: Get info of food based on barcode
      operationId: getOpenFoodFactsModel
      parameters:
        - name: barcode
          in: query
          description: Barcode number passed in through scan
          schema:
            type: string
      responses:
        '200':
          description: Model of the product information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenFoodFactsModel'
  /get-base-info:
    get:
      tags:
        - Hbv1
      summary: get info of the ingredient through Halal Nutrition API
      operationId: getBaseInfo
      parameters:
        - name: qStr
          in: query
          description: the ingredient in string form
          schema:
            type: string
      responses:
        '200':
          description: Model of the ingredient information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HalalNutriBaseModel'

components:
  schemas:
    OpenFoodFactsModel:
      type: object
      properties:
        code:
          type: string
        product:
          $ref: '#/components/schemas/FoodInfoModel'
        status_verbose:
          type: string
    FoodInfoModel:
      type: object
      properties:
        additives_n:
          type: integer
        allergens:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/IngredientModel'
        product_name:
          type: string
    IngredientModel:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        vegan:
          type: string
        vegetarian:
          type: string
    HalalNutriBaseModel:
      type: object
      properties:
        message:
          type: string
        entityData:
          type: array
          items:
            $ref: '#/components/schemas/HalalNutriModel'
    HalalNutriModel:
      type: object
      properties:
        label:
          type: string
        atribute:
          $ref: '#/components/schemas/HalalNutriAttrModel'
    HalalNutriAttrModel:
      type: object
      properties:
        certificate:
          type: string
        hasManufacturer:
          type: string
        type:
          type: string
    ProdInfoModel:
      type: object
      properties:
        name:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/ProdInfoIngredientModel'
        additives:
          type: array
          items:
            $ref: '#/components/schemas/ProdInfoAdditiveModel'
        isHalal:
          type: boolean
        companyName:
          type: string
        manuLocation:
          type: string
        imageLink:
          type: string
    ProdInfoIngredientModel:
      type: object
      properties:
        name:
          type: string
        halalStatus:
          type: string
    ProdInfoAdditiveModel:
      type: object
      properties:
        name:
          type: string
        halalStatus:
          type: string
        description:
          type: string
    QuestionInfoModel:
      type: object
      properties:
        question:
          type: string
        numViews:
          type: int
        numLikes:
          type: int
        answerList:
          type: array
          items:
            $ref: '#/components/schemas/AnswerInfoModel'
    AnswerInfoModel:
      type: object
      properties:
        answer:
          type: string
        answererName:
          type: string
